### ISSUE TITLE
the distance scalar $^{G}d$ in III-B

### ISSUE THREAD

**Issue by Hello-Water** [rpng/ov_plane#1]
![image](https://user-images.githubusercontent.com/30867133/230870563-4f5511d2-5aaa-4616-a34c-21b13b4872d8.png)
Here, maybe the distance scalar $^{G}d$  should be equal to $||\boldsymbol\pi||$.
Well, i misunderstood, and now i got it.

**Comment by ccchu0816** [comment]
Feel free to open if you have any further questions.
