### ISSUE TITLE
How to test without SLAM point and plane features 

### ISSUE THREAD

**Issue by tp02134** [rpng/ov_plane#2]
Hello.

Thank you for your contribution.
How to edit configuration options for not using both SLAM point and plane features?

Thank you.

**Comment by ccchu0816** [comment]
Thank you for your interest in our project.
You can modify the launch file in the following ways:

-To disable the use of SLAM plane features:
arg name="use_plane_slam_feats"  default="false" 
-To avoid using SLAM point features:
arg name="num_slam"              default="0" 

Feel free to ask if you have any more questions.

**Comment by tp02134** [comment]
Thank you for your reply!

So, what is the meaning of _max_slam_in_update_, _use_plane_constraint_slamu_, and _use_plane_constraint_slamd_ in the config file?
I would like to compare your algorithm with other VIO algorithms.

Thank you.

**Comment by ccchu0816** [comment]
As commented in the config:
use_plane_constraint_slamu: true  # use point on plane constraints for SLAM point update
use_plane_constraint_slamd: true  # use point on plane constraints for SLAM point delayed initialization

These specify if the point-on-plane constraint is used when performing SLAM POINT feature updates and initialization. 
The constraint can be referred to Eq.(12) in the paper, and more details about when to apply these can be found in UpdaterSLAM.cpp.

max_slam_in_update denotes how many POINT features can be used as SLAM features during the update.

**Comment by tp02134** [comment]
Thank you for your answer!
